# Generated by Django 3.1.2 on 2020-10-07 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kenzie_connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penpal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penpal_message', models.CharField(max_length=500)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_fk', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
