# Generated by Django 3.1.2 on 2020-10-09 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kenzie_connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_activity',
            field=models.CharField(choices=[('PS5', 'PS5'), ('Dungeons and Dragons ', 'Dungeons and Dragons'), ('Hackathon', 'Hackathon'), ('Dinner', 'Dinner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_booze',
            field=models.CharField(choices=[('Beer', 'Beer'), ('Wine', 'Wine'), ('Cocktails', 'Cocktails'), ('No Alcohol Please', 'No Alcohol Please')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_date',
            field=models.CharField(choices=[('Late-nighter', 'Late-nighter'), ('Early Evening', 'Early Evening'), ('Weekend Afternoon', 'Weekend')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_dog',
            field=models.CharField(choices=[('Jack Russell – small, tough, opinionated', 'Jack Russell – small, tough, opinionated'), ('Tibetan Mastiff – or some other very rare breed', 'Tibetan Mastiff – or some other very rare breed'), ('German Shepherd – poised and elegant but rather hardy', 'German Shepherd – poised and elegant but rather hardy'), ('Poodle – beautifully presented but a bit of a poser', 'Poodle – beautifully presented but a bit of a poser'), ('Golden Retriever – warm, cuddly and great with children', 'Golden Retriever – warm, cuddly and great with children'), ('Pit Bull Terrier – scary but kind deep down', 'Pit Bull Terrier – scary but kind deep down'), ('Labradoodle – or some other cute hybrid', 'Labradoodle – or some other cute hybrid')], max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_mind',
            field=models.CharField(choices=[('Cheeky Child', 'Cheeky Child'), ('Tormented Teenager', 'Tormented Teenager'), ('Mad Mid-lifer', 'Mad Mid-lifer'), ('Groovy Grandparent', 'Groovy Grandparent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_pet',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Dogs and Cats', 'Dogs and Cats'), ('No Pets', 'No Pets')], default='No Pets', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_pjs',
            field=models.CharField(choices=[('Never', 'Never'), ('100% Yes', '100% Yes'), ('Business on top, pjs on bottom', 'Business on top, pjs on bottom'), ('Literally took them off 1 min ago', 'Literally took them off 1 min ago')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_sleep',
            field=models.CharField(choices=[('Early Bird', 'Early Bird'), ('Night Owl', 'Night Owl')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_star',
            field=models.CharField(choices=[('Darth Vader', 'Darth Vader'), ('LukeSky Walker', 'Luke Skywalker'), ('Han Solo', 'Han Solo'), ('Princess Leia', 'Princess Leia'), ('Padme Amidala', 'Padme Amidala'), ('Jyn Ersp', 'Jyn Ersp'), ('Yoda', 'Yoda'), ('Chewbacca', 'Chewbacca'), ('Jar Jar Binks', 'Jar Jar Binks')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenzie_connect.penpal')),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
